(uiop:define-package #:cl-gme
    (:use #:cl #:cffi)
  (:export #:with-file
           #:with-track
           #:gme_clear_playlist
           #:gme_delete
           #:gme_enable_accuracy
           #:gme_equalizer
           #:gme_free_info
           #:gme_identify_extension
           #:gme_identify_file
           #:gme_identify_header
           #:gme_ignore_silence
           #:gme_load_custom
           #:gme_load_data
           #:gme_load_file
           #:gme_load_m3u
           #:gme_load_m3u_data
           #:gme_mute_voice
           #:gme_mute_voices
           #:gme_new_emu
           #:gme_open_data
           #:gme_open_file
           #:gme_play
           #:gme_seek
           #:gme_seek_samples
           #:gme_set_equalizer
           #:gme_set_fade
           #:gme_set_stereo_depth
           #:gme_set_tempo
           #:gme_set_user_cleanup
           #:gme_set_user_data
           #:gme_start_track
           #:gme_tell
           #:gme_tell_samples
           #:gme_track_count
           #:gme_track_ended
           #:gme_track_info
           #:gme_type
           #:gme_type_list
           #:gme_type_multitrack
           #:gme_type_system
           #:gme_user_data
           #:gme_voice_count
           #:gme_voice_name
           #:gme_warning
           ))
